### ISSUE TITLE
[Sample App] Note titles and contents not visible on Notes List screen

### ISSUE THREAD

**Issue by jmcaffee** [nhaarman/Triad#9]
After adding a note and saving, the Notes List screen displays blank item. Clicking the item takes me to the Edit Note screen as expected, and the note data is as expected.

It appears that `acquire` needs to be called on the `presenter` after the view is created in `NotesListView`.

``` java
    @Override
    public View getView(final int position, final View convertView, final ViewGroup parent) {
      NoteContainer noteContainer = (NoteContainer) convertView;
      if (noteContainer == null) {
        noteContainer = (NoteContainer) LayoutInflater.from(getContext()).inflate(R.layout.view_note, parent, false);
        noteContainer.setPresenter(new NotePresenter());
        noteContainer.getPresenter().acquire(noteContainer);  // <----- Add acquire to set container.
      }
```

Note: While I've figured out where to add the `acquire`, I don't know where to add the `releaseContainer`call, or if it is necessary in this situation.

**Comment by nhaarman** [comment]
`Presenter.acquire(...)` will automatically be called when the `View` is attached to the window. That would make this call to `acquire(...)` redundant. Releasing the `Container` will also automatically happen as soon as the `View` is detached from the window, so I don't think this will bring any trouble.

The actual problem is that the `NotePresenter` retrieves the `Note` before it acquires the `Container`. Upon requiring the `Container`, nothing happens. See #12.
